### ISSUE TITLE
Output file is empty for Oxford Nanopore simulation. 

### ISSUE THREAD

**Issue by dantaki** [ethanagbaker/SiLiCO#5]
Hello here are my commands
```
$ python /home/usr/SiLiCO-1.0.1/SiLiCO.py -i /home/usr/fasta/human_g1k_v37.fasta -n
```
STDOUT:
```
preparing the genome file.
The Scratch dir already exists. Cleaning up...
Done!
Generating a genome index file...
Done!
Generating simulated reads in Oxford Nanopore mode...
Building threshold dictionaries...
Calculating distribution parameters...
Completed trial 2 of 1. (200.0%)
Done!
Exiting...
```

Output:
```
$ ls 

SiLiCO_Scratch  simulated_read_positions_trial_1.bed.gz

$ less simulated_read_positions_trial_1.bed.gz | wc -l

0
```

I extract and read the file and it's empty. My python version is: `Python 2.7.13 :: Anaconda 2.3.0 (64-bit)`

Any help would be appreciated!

Thanks!

**Comment by ethanagb** [comment]
Hello,

Can you give me an idea of how your reference file is formatted? SiLiCO is
very particular about this and it may be an easy fix to your problem.

**Comment by dantaki** [comment]
Sure. The FASTA file is your standard hg19 from the 1000 Genomes Project

Here's `head` ran on the file

```
>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

Is there a particular format for the FASTA file? I couldn't find that information in the README or maybe I missed it 

Edit:  Is it because the chromosome header is not prefixed with "chr"? 

Edit Edit: Ok I tried running it with the hg38 fasta from 1000 Genomes 

```
$ head GRCh38_full_analysis_set_plus_decoy_hla.fa

>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

I get this error now

```
Preparing the genome file.
The Scratch dir already exists. Cleaning up...
Traceback (most recent call last):
  File "/home/usr/SiLiCO-1.0.1/SiLiCO.py", line 166, in <module>
    main(sys.argv[1:])
  File "/home/usr/SiLiCO-1.0.1/SiLiCO.py", line 134, in main
    names = splitGenomeFasta(infileName)
  File "/home/usr/SiLiCO-1.0.1/splitGenomeFasta.py", line 37, in splitGenomeFasta
    fastaNames = [str(x.split('/')[1]) for x in fastaNames] #Cleaning of names
```

Edit Edit Edit: 
I wrote a quick script to change the FASTA headers to `chr1` and the like

```
head hg19.fasta
>chr1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

I still get this error

```
$ python /home/usr/SiLiCO-1.0.1/SiLiCO.py -i hg19.fasta -n
Preparing the genome file.
The Scratch dir already exists. Cleaning up...
Traceback (most recent call last):
  File "/home/usr/SiLiCO-1.0.1/SiLiCO.py", line 166, in <module>
    main(sys.argv[1:])
  File "/home/isr/SiLiCO-1.0.1/SiLiCO.py", line 134, in main
    names = splitGenomeFasta(infileName)
  File "/home/isr/SiLiCO-1.0.1/splitGenomeFasta.py", line 37, in splitGenomeFasta
    fastaNames = [str(x.split('/')[1]) for x in fastaNames] #Cleaning of names
```

**Comment by ethanagb** [comment]
Try with header lines of >chr1 only, the software does expect that...this
is something I've been meaning to improve.

eg:

>chr1
ATGATATATATATATATATATATATACCAC
ATACGCGATAGATATGACACAGTACAT

If that doesn't work, happy to investigate further.

2017-07-05 11:53 GMT-04:00 Danny Antaki <notifications@github.com>:
