### ISSUE TITLE
TypeError: memoryview: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by jnarayan81** [ethanagbaker/SiLiCO#7]
It terminated with following error !
```

➜  SiLiCO git:(master) ✗ python SiLiCO.py -i /media/urbe/ARCgenomic/toyGenome/toy.fasta -o toyGenomeONTReads -n -m 20000
Preparing the genome file.
The Scratch dir already exists. Cleaning up...
Done!
Generating a genome index file...
Done!
Generating simulated reads in Oxford Nanopore mode...
Building threshold dictionaries...
Calculating distribution parameters...
Traceback (most recent call last):
  File "SiLiCO.py", line 166, in <module>
    main(sys.argv[1:])
  File "SiLiCO.py", line 151, in main
    simulateReads(infileName,outfileName,mean,std,desired_cov,trialCount,names, SEQ_MODE)
  File "/home/urbe/Tools/SiLiCO/simulateReads.py", line 143, in simulateReads
    outfile.write(str(selected_chrom) + '\t' + str(start_pos-correctionDict[str(selected_chrom)]) + '\t' + str(end_pos-correctionDict[str(selected_chrom)]) + '\t' + 'trial_'+str(trial_counter) +'_sim_read_' + str(name_counter) + '\n')
  File "/home/urbe/anaconda3/lib/python3.6/gzip.py", line 260, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'

```

**Comment by ethanagb** [comment]
From the traceback, it appears you're running this in a Python 3
environment. Can you try in Python 2.7?

**Comment by jnarayan81** [comment]
Hmmm, I build and install with Python3 that might have cause the error. Now it is fixed with Python2.7
Thanks for your favor.
